-- 5. Payment Behaviour
 
SELECT OP.payment_type , SUM(OP.payment_value) AS PAYMENT_VALUE, COUNT(OP.order_id) AS NO_OF_PAYMENTS,
SUM(OP.payment_value)/COUNT(OP.order_id) AS AVG_ORDER_VAL
FROM order_payment OP 
JOIN orders O 
ON OP.order_id = O.order_id
where O.order_status = 'delivered'
group by OP.payment_type 
ORDER BY PAYMENT_VALUE DESC;

-- THE MOST USED PAYMENT MODE IS CREDIT CARD, FOLLOWED BY BOLETO, VOUCHER AND DEBIT CARD.
-- THE AVG ORDER VALUE OF VOUCHERS IS SIGNIFICANTLY LOWER THAN THE OTHERS, SO WE CAN SAY THAT THE 
-- TRANSACTIONS MADE BY THE VOUCHERS ARE OF LESS VALUE.

SELECT OP.payment_installments , SUM(OP.payment_value) AS PAYMENT_VALUE,
COUNT(OP.order_id) AS NO_OF_PAYMENTS,
SUM(OP.payment_value)/COUNT(OP.order_id) AS AVG_ORDER_VAL
FROM order_payment OP 
JOIN orders O 
ON OP.order_id = O.order_id
where O.order_status = 'delivered'
group by OP.payment_installments 
ORDER BY AVG_ORDER_VAL DESC;

-- THE AVG ORDER VALUE OF PURCHASES MADE IN HIGHER INSTALLMENTS ARE CLEARLY HIGHER SO THIS IMPLIES THAT 
-- FOR BIGGER PURCHASES PEOPLE OPT FOR HIGHER NUMBER OF INSTALLMENTS.
-- IF WE TALK ABOUT THE MOST REVENUE AND MOST NUMBER OF PURCHASES COMES IS SINGLE TIME PAYMENT. 

SELECT   OP.payment_type, OP.payment_installments , SUM(OP.payment_value) AS PAYMENT_VALUE, COUNT(OP.order_id) AS NO_OF_PAYMENTS,
SUM(OP.payment_value)/COUNT(OP.order_id) AS AVG_ORDER_VAL
FROM order_payment OP 
JOIN orders O 
ON OP.order_id = O.order_id
where O.order_status = 'delivered'
group by OP.payment_type, OP.payment_installments 
ORDER BY AVG_ORDER_VAL DESC;

-- WE CAN SEE THAT ALL THE MULTIPLE INSTALLMENT PAYMENTS ARE DONE WITH CREDIT CARD AND ALL OTHERS MODES 
-- ARE USED ONLY FOR SINGLE INSTALLMENT PAYMENTS.
-- MOST REVENUE COMES FROM THE PAYMENTS DONE WITH BOLETO IN SINGLE INSTALLMENTS FOLLOWED BY SINGLE INSTALLMENT
-- PAYMENTS BY CREDIT CARD. 
-- BUT THE MOST NUMBER OF TRANSACTIONS ARE DONE IN SINGLE INSTALLMENT PAYMENTS BY CREDIT CARD FOLLOWED BY 
-- SINGLE INSTALLMENT PAYMENTS BY BOLETO.

SELECT C.customer_state , OP.payment_type, SUM(OP.payment_value) AS PAYMENT_VALUE, 
COUNT(OP.order_id) AS NO_OF_PAYMENTS
FROM order_payment OP
JOIN orders O
ON OP.order_id = O.order_id
JOIN customers C 
ON O.customer_id = C.customer_id
WHERE O.order_status = 'delivered'
GROUP BY C.customer_state , OP.payment_type
ORDER BY C.customer_state , PAYMENT_VALUE DESC;

-- THIS QUERY SHOWS THE TOTAL REVENUE, NO OF PAYMENTS AS PER THE PAYMENT TYPE IN EACH STATE.
-- THE STATE OF SP GENERATES THE MOST REVENUE THROUGH CREDIT CARD, FOLLOWED BY RJ (CREDIT CARD), 
-- MG(CREDIT CARD) , SP(BOLETO), RS(CREDIT CARD). 